---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argopj.io
spec:
  project: default

  # Source of truth (your new Git repo)
  source:
    repoURL: 'https://github.com/bigbrovar/kraken-config.git'
    targetRevision: HEAD
    path: platform # <-- This is the directory it will watch

  # Destination (our local k3s cluster)
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  # Sync policy (This is the GitOps magic)
  syncPolicy:
    automated:
      prune: true    # Automatically deletes things that are removed from Git
      selfHeal: true # Automatically corrects any manual changes (drift)
    syncOptions:
      - CreateNamespace=true # Allows ArgoCD to create namespaces
