---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.longhorn.io'
    chart: longhorn
    targetRevision: 1.7.2
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 2
          reclaimPolicy: Retain
        defaultSettings:
          defaultReplicaCount: 2
          createDefaultDiskLabeledNodes: false
          defaultDataPath: /var/lib/longhorn
          guaranteedInstanceManagerCpu: 5
          replicaSoftAntiAffinity: true
          storageOverProvisioningPercentage: 200
          storageMinimalAvailablePercentage: 10
        ingress:
          enabled: false
        longhornManager:
          tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
        longhornDriver:
          tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
        longhornUI:
          tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        maxDuration: 5m
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /status
