---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: vault
    targetRevision: 0.28.1
    helm:
      values: |
        global:
          enabled: true
          tlsDisable: true

        server:
          # PRODUCTION MODE - Data persists!
          dataStorage:
            enabled: true
            size: 10Gi
            storageClass: longhorn
            accessMode: ReadWriteOnce

          # HA mode with Raft storage (works across restarts)
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true
              setNodeId: true
              config: |
                ui = true

                listener "tcp" {
                  tls_disable = 1
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                }

                storage "raft" {
                  path = "/vault/data"
                }

                service_registration "kubernetes" {}

          # Ingress for UI access
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - host: vault.homelab.org.ng
                paths: [/]
            tls:
              - secretName: wildcard-homelab-tls
                hosts: [vault.homelab.org.ng]

        injector:
          enabled: false

        ui:
          enabled: true

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
