---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Name for the app card in ArgoCD UI
  name: vault
  # Tells ArgoCD where this Application lives
  namespace: argocd
  # Ensures all components deleted if app deleted
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  # Part of the "default" project in ArgoCD
  project: default

  source:
    # Official HashiCorp Helm chart repository
    repoURL: 'https://github.com/bigbrovar/kraken-config.git'
    # The chart name to install
    chart: vault
    # Recent stable version
    targetRevision: 1.27.0

    # Helm values to configure Vault for homelab
    helm:
      values: |
        # Runs Vault in "dev" mode (lightweight, auto-unseals)
        # Uses in-memory storage. NOT for production.
        global:
          enabled: true
          tlsDisable: true

        server:
          enabled: true
          # Run in dev mode
          dev:
            enabled: true

        # Don't need these for basic setup
        injector:
          enabled: false
        csi:
          enabled: false
        ui:
          # We want the UI
          enabled: true

  # Where ArgoCD will deploy Vault
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault

  # GitOps sync policy
  syncPolicy:
    automated:
      prune: true  # Clean up old components
      selfHeal: true  # Fix manual changes

    # Create the vault namespace automatically
    syncOptions:
      - CreateNamespace=true
