apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # This is the name for the app card in the ArgoCD UI
  name: vault
  # This tells ArgoCD where this Application manifest lives
  namespace: argocd
  # This ensures all of Vault's components are deleted if we delete this app
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  # This app is part of the "default" project in ArgoCD
  project: default
  
  source:
    # Use the official HashiCorp Helm chart repository
    repoURL: 'https://helm.releases.hashicorp.com'
    # The name of the chart to install
    chart: vault
    # A recent, stable version of the chart
    targetRevision: 1.27.0 
    
    # Helm values to configure Vault for our homelab
    helm:
      values: |
        # This is the most important part for a homelab
        # It runs Vault in "dev" mode, which is lightweight,
        # auto-unseals, and uses in-memory storage.
        # This is for learning and IS NOT for production.
        global:
          enabled: true
          tlsDisable: true # Disables TLS; we'll add our own Ingress later
        
        server:
          enabled: true
          # This runs it in "dev" mode
          dev:
            enabled: true
        
        # We don't need these extra components for our basic setup
        injector:
          enabled: false
        csi:
          enabled: false
        ui:
          enabled: true # We want the UI

  # This is where ArgoCD will deploy Vault
  destination:
    server: 'https://kubernetes.default.svc' # This means the local cluster
    namespace: vault # We'll put Vault in its own "vault" namespace
  
  # This is our GitOps sync policy
  syncPolicy:
    automated:
      prune: true    # Clean up old components
      selfHeal: true # Fix any manual changes
    
    # This tells ArgoCD to create the "vault" namespace for us
    syncOptions:
      - CreateNamespace=true
