---
name: Validate Kubernetes Manifests

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # CHECK 1: YAML Syntax
      - name: Set up yamllint
        run: pip install yamllint

      - name: Run yamllint
        # Scans the whole repo for YAML syntax errors
        run: yamllint .

      # CHECK 2: Kubernetes Schema Validation
      - name: Set up kubeconform
        run: |
          curl -Lo kubeconform.tar.gz \
            https://github.com/yannh/kubeconform/releases/download/v0.6.6/kubeconform-linux-amd64.tar.gz
          tar xf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin/

      - name: Run kubeconform
        # Validates YAMLs against official K8s schema
        # Smart enough to find only Kubernetes manifests
        run: kubeconform -summary -kubernetes-version 1.30.2 .

      # CHECK 3: Security & Misconfiguration Scan
      - name: Set up Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | \
          sh -s -- -b /usr/local/bin

      - name: Run Trivy
        # Scans manifests for security issues
        # Fails if HIGH or CRITICAL issues found
        run: trivy config --exit-code 1 --severity HIGH,CRITICAL .
