---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "51" # Deploy after Mosquitto
spec:
  project: default
  source:
    repoURL: 'https://github.com/bigbrovar/kraken-config.git'
    targetRevision: HEAD
    path: configs/energy/influxdb
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: energy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
