actualbudget:
  image:
    repository: actualbudget/actual-server
    tag: "25.1.0"
    pullPolicy: IfNotPresent
  
  persistence:
    enabled: true
    size: 5Gi
    storageClass: "longhorn"
    accessModes:
      - ReadWriteOnce
  
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/issuer: "null"
      cert-manager.io/cluster-issuer: "null"
    hosts:
      - host: actual.homelab.org.ng
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: wildcard-homelab-tls
        hosts:
          - actual.homelab.org.ng
  
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 512Mi
