{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "checkrr-secrets",
    "namespace": "media"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "checkrr-secrets",
        "namespace": "media"
      }
    },
    "encryptedData": {
      "radarr-apikey": "AgBTaCtrQXlhD5O033nu+GldF/pISIQtfHgdHYTry1YIfl6W0F8A3Yk9zYWa1KRXAaZjY+CkJWDN5L6/UBOG1w3J8/ZUUd++RxkF73oVznzCOcRI8x8biDXUoECwbcy8NcTNdl1/gMiDNHR+mokcA44oaQORfZ9cKHlT0dTPMmBbLbhLnzP0WFKLkP/M5loaZ6thnqSvD724xuvnjLQVb+GVQSOAtj7h2bLaXFxx/SFH3R9AXNbFBYvOibJojj/7/KBofNv+lYZvV/K7Tj8+U9rMpYKeiXoCBeA/rgaQn9Tj/77qT7bBqp3i5+htzwet4YULPnDwbNhz2fCHiPmTdq9cD9ZyE028DIxHYCqF6NYHp/2qSGlNWoEzafikSZ5xfJjYZW9Tt/wUrtL++yjk8sjP9uBvgoR2yGEuoX2TzDVPlD4r4C4saz/jwGHoLz5w1TkjOmbdh5EyYi73as9zH2C+7X6IKQXhUdbswnFUvSuS87xa5dvdKCY5yHE9MDvWf1VoOHWcStxNnvOmjgtd76lMNax9cHYhtZgqY7dcWaiDxYVic9Ckw2MZfwEZ2ZfmtFuHCOOAeTg0i5/xd1N5A1iCxIojNyQXL9Cj8JciJ1OycNcRjWIvtYfI4PKnDSELf0cy9f4+N2tkTASusoVCuQ/PMgfbh1Ac5S9EdyztrJrqMxYJ1d3Ojq4WP/z/IlMlQdHI6u1TRjQE8zMtgbP4EZnvBFPfEseZlXldPHOKNwZWgQ==",
      "sonarr-apikey": "AgAZUIKFIJU0j8KSYY8/1b7XDHIUiPBHLsYrC9OX6UHDHZmho8FWq7wfF8ti+hXFZMVXbUQ3njd0FpIFYSwROaEH3ay1mGjwxVkjpJW3NUggQO99vACNoTz9hBiwFUSbOkqvjhI5GSPPhmfspd9M0kfnyFnX5G2uMpA07nv354pEXENHcUxOXheYnswWsJMWiMB/6NUSRA9eMP2EkNo/p6XKMktHnmvPqGZYFcT8MoipOI5YKq17kA+AixnGU4r2Qm41hggq0R3lLjg0VPFYkhV8ixF1Vp+zaTQP53FB6d0icp+wJowy0SwSfS+AyO7J8BRyH05A5K8J8sDcdASYUfKgegwatlaZtr+Ak9VxQbYRSoD7BJGPGErOp1706w8afwVlAha4/Vx0oMga1BeaS1ksS/uImANWuu8fZtxTMI7qaW9qI9wzlA3uxAebQtpmMROT9x2hVMO1tlyIwU6OkK0pvmPlAE2YMUhIGCYmeLQUWlCl9M8Nz8tMtbBLNlKFrmoLRuEsnqpgFwoEDbx7YOns6byTjhZa9gfIXjXMaRw//bRGYWOF2uFmlkjWV19rC7nO9ihraoGN+l7VX+gq9mNNKYLWBnEk2DaOqdhUL37Ttx7t+Vh9plCfoXQTLligbpSvVj7bFsG7Bllrr3eRwp1g8yF02qZrAUkErUydLkDxSlVhdO3SkM32N9WM2OFdvLx17ssigR9MtHY8GAQfJMBJQMnuW7pz72zh9N9fElXznw=="
    }
  }
}
