{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "cert-manager"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "cert-manager"
      }
    },
    "encryptedData": {
      "api-token": "AgCZHBtRc4OrkO7M64LIxA/LMvEQHEFWfIxEe/nMobT95C93Ep1NPoZnrldpl2RvlCq0NV6QElOk5pvL9oUsf2UMF/5uXaoEjcP4OpwKEe35Cx1Mp4nbhkLZZixyjyXvMVIOawMBoR7qaF20zw7JveEFI+sGtu/VTv6JsQTif/TBr/NMqp7cHQ1mH3NP4AQzERkL04nBMzXzHEfEAJPxgNTbT09LFR3CZoSxcSotTU3u2YKUKRcNgqGrOE750qr4uIVktMiYdmeMwHNCTWOXdwmuHY6L9oQH18s+fe7oGePIJ+DkwBuoOXvreaMQQDUmJAsR7kxLpiuDVqjh2vOlvNam+4bmutIBElL48tyKUAz9vWtYwfTZRV7TBOtCHAH9BCg3DOVvEEhE5UrH3MeT/Os4gZ7euCChjw7SQorBH9FWuU25ApqPBfRomSE/GUfJwgFxGYoG65GBekaUIHqmM508COIUjHYsxDwWeyHe1Gcn1KGPz0+5dt+uA2o92mAfls2b2gvZez+O6JnKApAkdvznghalGo8gTHQPH72LTSEVp4zDphvaympKOgkwxtHqx4NeelhVLBrAq/dfVB+80WRRZjrr8XiXNUvaSXXafuHshw2weN4Vy+uv7yBm3miIi8N03D5ibxaHdDVBeobzJo5F0k/xfG6CfH9EKKRJhS5BAgEJJBcx2h7C8haxmIvGAMCMDMIE+MACNQWj7iSpvODPUyltnzzaRMb5E/v8ppusqu0xe4cnKXqU"
    }
  }
}
