{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mosquitto-auth",
    "namespace": "energy"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mosquitto-auth",
        "namespace": "energy"
      }
    },
    "encryptedData": {
      "password_file": "AgCs35GkiYi7aUy8dHYmn8tJAmDh+eZcRUt+kkB0Mh09I8NUx7CxlPufEBTbp+2RBS7XPbNW2agyR5lCDqiT6S3VOyczCGJt9v/1NLeT7DfRhkSRlwK/FIISGizjrYAgIM2wLhqZu6H5KLrdwiIDZSxHvept6Ck+A2pzLjoDfS8YwyLwlgN2uFTRJyTSRBTMd0r7rifyZuvbeTMRy1SLp/hZLEXfiV6+4pqRwy8ERoLjI921bapDR1gl8a45lKGbWLuEgF5OvrC6hWkWGlJ1VLzRINpSEnevvFlj8ikdbRUrldy3mBiaELxTrmW2bFnpfwIYPN/GO/vga9u0ViRO1B1AmfLDyjCfj/eOIlDjkovVJAeTj6sRhJ6IIkeeknHLRmzIm4F2ZHj0sVXaMKSu5/+7xb4M1W5rBMOSH5fnSRPpX+ITqO6BfCSGcg/w0uNDJFf4VAZBHasY6HG/CDIxohs9GOkPKX25rzNn5/37EHJupdArH0OG5E61E1HU4SaBT0yHcsT0Zi49shrckRJ7wv6HzYdL/ma7HRsNEWub/bBkV8rvJqbXUigJWOiFUk+hrG+qc3iN4Gt7xL1/bE/HEctDrRvDlPDEw4G4RmT4PHi4EharTDB7XegCbZvr8RPxTnYZCuC8A2fNY6Nde/32h83+OkKpHgNEZOR+hNIeP0hzaxxdiwxhLxmRPrpGDK/BJrwao0emS5qqZ3gP8nlJDWBBKrT0Mjo/HzNKzB6fD0rvdmR3atULI+MMR5wz2Y4Efw=="
    }
  }
}
