{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mosquitto-auth",
    "namespace": "energy"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mosquitto-auth",
        "namespace": "energy"
      }
    },
    "encryptedData": {
      "password_file": "AgBa7/DR22X9iU3Lf3EklIdab9LIXr1sPspwbUH/Dg0pdVLYZ3MWkwskTYO54+2CVsJjNrnWiyJXuYma76Mg2OUcioSvrKLKxs1AMsQKjMAIIGWHxHWtwardEyInCMf8LzdcjhIwXBsTBFssiXGrhyty6xwrHgFn+cnfGaVIuKBGcAp9dhTNVk8P2bFI/fIrYnHrewhhmWL96/gxvUtM0DjvHsHgQMZtxtVcwybCBq4pHAFI03eHJDXevn43RDUS+G7xOLfwI5s/DhiHcnHAHQnlkozbCZ3aj3Od+CqF+u0pBFmB7uCoIoFlnXdasDiMNF58m6x5V5aMehQDFcdy8VR5K/PbL4t9JDiAIW7UYsXlnX9/n/ogh8OXu7mEWZ1NzWDUMxj5yEWXsK7AqFNMTun9NH6EXcDtrGkA3klFjCaa2CKZoYMKK6zXdQXfBBc/FB8Zu7nwqrTj4PabCBkRhdZtPMIbij2syIr+pEIAREZ5ctjajaVv2S6ggL+6UeWiwyLpHXbSaFruAgCQQQt2nqq6d6kwQ+AznkGJGPgXbckFiwBHiEcF26eA6n86opMFfwVSwbVlEGY/uUDLX31by6UEbyvMeDV9Cwy3WNpDCPm1HVfrUwA8VYypNThzUXtC+hfeHk36FbC0Zcd6dPR5oY0Qz6YD6SxsZGPn/Oa2bbxknwFqyw025Y+aGtTh+9CntWWF8OtODn3ROk/mQOK5OWQOBbsyv+qhhsjSXptNkFNXeBoBtlDfAMkzgcAEbGIOrg=="
    }
  }
}
