---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secrets
  namespace: media
spec:
  encryptedData:
    SEARXNG_SECRET_KEY: AgAow2AQg0+F3hTmIfGW34csWe5gzkGP/ZSDdyDQR2lCXt8IbTT9BOROltUwe+HnCxhpGxUDL5GUdeXAKJlOfPsi8TJnNrvPheMLRqOf9RC4Jzf7VaF17D+sOKHZ4KtFSLdXbIP+hYTESVEoFDyP002pgt3wywxHgigSrNNleQQVdcdPCnBwmEt5TcSzV9caO6RfegY/Ag1Op4PPaeVn/GK0njaJJwL9rOSqOlO+3Ny+anF11s5QPBdlxQ8vmtRDq80s4OJULTZvVTAG7jVkav4BmZEql+S7i11AN/RsP1NQNLyu2jIt8+fOYLWlsHc6Qsb7Uyrw3hH+AvhCJUnIM6GL/y7DLqO2HOrMbZMhLVdEwCFMOmtQjUmCwdyDWll464Cy8jXm33a6UwZIKMmcGkWa2O2rxIwrCGS2zGz9TRAaMaqvrv41By+dOp4Yt0ea42bXdeAuBZPF8nsctEmrFC0+MpacpuLStNARdlLc4WdO8mTHhi/ei0VmP6smfWqCxCsTVXcvpQklvq7LurUJZ9xovAOOstdb08Bf3zEQ4sG48+Qzm9tEt9/t/q63m4Fj2Lh2CTWrGt52SeS8jjIwph/Bk6TVrnc9SwaC6Iq7QtvfVyOXTl9RQ4fk3z3ESDYeUKt4Ij/fQtIOe+Tf4XjNGPtI2cLJH3AnrVUzz/tyOOlU7oqqPSnp3lNdafIr6AlE2Z86vW8ndi3iLZ36RqE5oNpkWVJ/zw8K5kDuyd8YuVSIRXjWwCv+oDnnnIvn3u4GcD66C0uKAr06F7aDkEDgFkV2
  template:
    metadata:
      name: searxng-secrets
      namespace: media
