{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "telegraf-secrets",
    "namespace": "energy"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "telegraf-secrets",
        "namespace": "energy"
      }
    },
    "encryptedData": {
      "influx-token": "AgBd7B4ED/rDRxeufHyFY18JynqBlTytT9UnGal+K1vu1nbbu+mF28BjFFKqiF9iUfN9WfxuDGB4Cgv1od1Ff+sS/tM35JezPX9/1eKcvSGB3SrJj39eD0ZYVDxyMn77g8EnDz46ykU70RhkDHpef7Rd4w9AOw20itQHgcJnHJSlcFwDWxATRaMQ/gaqPfKmgOskx4yYLWOUzpTwCHZ69gW2gQihtnpXxIhjd70Z2Sb/ofClmBHw7ZLpiResbxGA3MwJz75ZbyF8EKsYikrCBAs2c5rMBvjggBn0g0/CEN0Hbuu/dqpvnC54ubyX4WvSyrIei2l0Wyp0HPf0McWBRaq+VS/1IajboeGUwo3fGiBvM0zK/tODTtJiXQfbsD9IA2hnSp+HnRefUf5c5q+I7zeM9Yi6Od4iYkOO5GtDNtqhlbCLOGpBZd+m2SseZUFchu9A8kvciqCzEzb5HbSuUN1yiAXdUleMss2bfmrnZNPUTZAo7pNezbQq0j0oShXu9Hjsi/rh+yiY9ma6mPWjrLJ/e0UBoeUAYMT4wFsh2QVGJudP5lFrJHZwp7SjMc+TmGGBfEpFs/+ehoMj035tzfAZZnXfz4tnkNfzcHAZ2zlqESVJaoWNqeexIhCvHCwcGMSJG9y1sHQySRDp9lrorjp/MF76OFFKj0l9ZTcHDwoKKhVs8VQF45fUWgs5F4LSH8fDisS6uvnQsrWZMgxXsLJLisnm1y13YThpicN3DnxtrQMV1nw64sXvIMRUpg==",
      "mqtt-password": "AgBw3CC+SO2YOqPSM4OSeSBSF2NPb5IAOiKHmgrtuJ8eMpll1Mw4STMnuPWe2BSetKzkmv4kq3Mo9awotn6ygfdvpRdPg3TCqYqg1tqYAaNXZ/LnrZ7kSGL1MxS566t9jYhUJUmVdDXK80inlFaczKbSd1sEqO+y7lrdz/ja4lnOXh6AwCFimqb0EoMiiUJ56uXNwwqX16JjVmheYTH8X+OptYJjZhU6T8T3QeCcjA3taXa1sn1qTuvdU9Skk3eZ+Y1Xn3KY9dJFXKWiC2ZTbgMhZvigAJA2x/vLBLhbxouANzqcdi7/el/cAVm29cTiHQ9hqZkkE8in4dNOw5OMEKq2duUiOFk36lMCKJqtK3yBtLxWfdIl9CXqOUnho87Z5lllgUtjcqsRcYVxDX+fhaDKICZn5tDhGrnVvhr+GfjD81B/5ooXWAeda+azMdhwa9ea/UdvsZ065OU1rqQzNAzU7JJCfD2TXy/FbJTsqUM2SMp/gRg85s7rFNk+PZqp/21OQ+Ykep1I3qqEqGL1pyX51yiMEdTxi35lI3xHrbqa3vkl7xDP1jFqfvq7YThpv2M9uuLlou++EVSEsu6+CAHXUr7BYQUJvBZbh2IeoDzX6KHKpQW1NmZIfgO4V8T6SsKwF7JiHvXfMHrPBva8IUAfRqB376cxZRtXR5aViWHcQCsI5ef+3D5nODmxg9RN/90OnxnD9SHRlkxjbwo/1auniS4=",
      "mqtt-username": "AgAg+7xC8WBC1equYvYORbU0KD16YC2VGqJa3ywcDQRQuhMeoFII34XbfD45ez3JnHuGajornD2KiZiz5BCWaUokATtKYtHerRUDzuofKR+JUkp2bjcxZgHdJW9VxHKz/fif9uBr8iUvoTsBIucPZKBSXRPF+v8e6zGvl9HqQ8e7QYsflMxI3o9R2kieLQIGCW9TFwhemvqQixVy7ZScPhCmXgvNGHWz+kyvmWWjB/QtrbsNAUYX5MLTKZIMZe0o+QqTCOEs65SleFvgTy8vx8HWqWsxJwrbNx3atujIQ9+SfGWtBHZ+weTRS5ENF2LMvbZxG6sLHIBltngp0iAJJxDp2DYyOkTr4iz3N2D/l+U7EIJEa6m0V5FNikLtAc0BGX82Dv6CWs6cXXT4XzqiiKNeBbJhgVQDXPyOCyJDufpSW0k/QvkJQbwzBmE9/bQSKFsrfWteQtf447BauzbOLDwo5EfyU6pF5c7nPlXqDx1B3HV/nU70h7wshjucba4cz1AqBWZFzNIPFLVNwAOV40y6j3mpcurF+/ofzcg5N/es8Y43qTN5RpEEDBWdj9CkX1W4OpfrsYIn9BIGPWpZIVbx2Vavm/oGN1TdFls00c1RzP/ne4/xstv1/MMbIJjT8GbmQB2C404WFEdfJI8w3PB7gMDdJjiE6n5O5Fs6vWWrh0KaglURRvelm0hOrU0qnt7ZiQYYOTwxcQ=="
    }
  }
}
